let pages = [
    {
        numb:1,
        image:'images/1.gif',
        name:'THE ALTERNATING HOOKS',
        time:'30',
        comment:'rotate your shoulder and hips  ',
        // comment:'valo koree karo hote see naa.',
    },
    {
        numb:2,
        image:'images/2.gif',
        name:'DUMBBELL KICKBACKS (15)',
        time:'30',
        comment:'ex-hale as you pullup the dumble and in-hale as you lower them. click the next task when you are done.',
        sets:'15',
    },
    {
        numb:3,
        image:'images/r2.jpg',
        name:'15 second rest',
        time:'20',
        comment:'take a rest. let your amrs relax.',
    },
    {
        numb:4,
        image:'images/3.gif',
        name:'DUMBBELL MILITARY PRESS.',
        time:'30',
        comment:'you should fill as like your hands are burning',
        sets:'15',
    },
    {
        numb:5,
        image:'images/4.gif',
        name:'DUMBBELL REVERSE CURL',
        time:'30',
        comment:'this exercise increase the strength of your shoulder',
        sets:'15',
    },
    {
        numb:6,
        image:'images/r1.jpg',
        name:'25 second rest',
        time:'25',
        comment:'take a rest. you can have some little drink',
        
    },
    {
        numb:7,
        image:'images/5.gif',
        name:'DUMBBELL FRONT RAISE',
        time:'30',
        comment:'pull your shoulders back',
         sets:'15',
    },
    {
        numb:8,
        image:'images/6.gif',
        name:'DUMBBELL SIDE LATERAL RAISE',
        time:'30',
        comment:'aaaaeeee please pull your shoulders back',
         sets:'15',
    },
    {
        numb:9,
        image:'images/7.gif',
        name:'ALTERNATE HAMMER CURL',
        time:'30',
        comment:'squiz your bicep at the top',
         sets:'15',
    },
    {
        numb:10,
        image:'images/r3.jpg',
        name:'30 second rest',
        time:'30',
        comment:'have a rest. your arms should be ',
    },
    {
        numb:11,
        image:'images/8.gif',
        name:'DUMBBELL TRICEPS EXTENSION',
        time:'30',
        comment:'please squiz your tryceps up while raising your hands up',
         sets:'15',
    },
    {
        numb:12,
        image:'images/9.gif',
        name:'STANDING DUMBBELL CURL',
        time:'30',
        comment:'squiz your bicep at the top',
    },
    {
        numb:13,
        image:'images/r4.jpg',
        name:'20 second rest',
        time:'20',
        comment:'have a rest. you should fell relaxed',
    },
    {
        numb:14,
        image:'images/2.gif',
        name:'DUMBBELL KICKBACKS (15)',
        time:'30',
        comment:'ex-hale as you pullup the dumble and in-hale as you lower them.',
        sets:'15',
    },
    {
        numb:15,
        image:'images/3.gif',
        name:'DUMBBELL MILITARY PRESS.',
        time:'30',
        comment:'you should fill as like your hands are burning',
        sets:'15',
    },
    {
        numb:16,
        image:'images/4.gif',
        name:'DUMBBELL REVERSE CURL',
        time:'30',
        comment:'this exercise increase the strength of your shoulder',
        sets:'15',
    },
    {
        numb:17,
        image:'images/r1.jpg',
        name:'25 second rest',
        time:'25',
        comment:'take a rest. you can have some little drink',
        
    },
    {
        numb:18,
        image:'images/5.gif',
        name:'DUMBBELL FRONT RAISE',
        time:'30',
        comment:'pull your shoulders back',
         sets:'15',
    },
    {
        numb:19,
        image:'images/6.gif',
        name:'DUMBBELL SIDE LATERAL RAISE',
        time:'30',
        comment:'aaaaeeee please pull your shoulders back',
         sets:'15',
    },
    {
        numb:20,
        image:'images/7.gif',
        name:'ALTERNATE HAMMER CURL',
        time:'30',
        comment:'squiz your bicep at the top',
         sets:'15',
    },
    {
        numb:21,
        image:'images/r3.jpg',
        name:'30 second rest',
        time:'30',
        comment:'have a rest. your arms should be ',
    },
    {
        numb:22,
        image:'images/8.gif',
        name:'DUMBBELL TRICEPS EXTENSION',
        time:'30',
        comment:'please squiz your tryceps up while raising your hands up',
         sets:'15',
    },
    {
        numb:23,
        image:'images/s (1).jpg',
        name:'TRICEPS STRETCH LEFT',
        time:'30',
        comment:'you should fell strech on your triceps',
    },
    {
        numb:24,
        image:'images/s (2).jpg',
        name:'TRICEPS STRETCH RIGHT',
        time:'30',
        comment:'you should fell strech on your triceps',
    },
    {
        numb:25,
        image:'images/s (3).jpg',
        name:'BICEPS STRETCH LEFT',
        time:'30',
        comment:'you should fell strech on your BICEPS',
    },
    {
        numb:26,
        image:'images/s (4).jpg',
        name:'BICEPS STRETCH RIGHT',
        time:'30',
        comment:'you should fell strech on your BICEPS',
    },
    ];